import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const htmlPath = join(root, 'dist-site/index.html');
const outDir = join(root, 'generated');
const outPath = join(outDir, 'home-html.ts');

const html = readFileSync(htmlPath, 'utf8');

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outPath,
  `// Generated by scripts/embed-home-html.ts — do not edit\nexport const homeHtml: string = ${JSON.stringify(html)};\n`,
  'utf8',
);

console.log(`Wrote ${outPath} (${html.length} bytes)`);
